# Usando a imagem oficial do MySQL versão 8.0 (estável)
FROM mysql:8.0

# (Opcional) copie um my.cnf customizado, se precisar
# COPY my.cnf /etc/mysql/conf.d/

# Expor porta padrão do MySQL
EXPOSE 3306
